apiVersion: v1
kind: ServiceAccount
metadata:
  name: crd-account
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-role
  namespace: default
rules:
  - apiGroups: ["otus.homework"]
    resources: ["pods", "deployments", "service", "pv", "pvc", "mysqls"]
    verbs: ["get", "list", "create", "update", "delete"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-acc-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: crd-account
    namespace: default
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: crd-role
  apiGroup: rbac.authorization.k8s.io