apiVersion: v1
kind: ServiceAccount
metada:
  name: crd-account

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-role
rules:
  - apiGroups: ["homework.otus"]
    resources: ["*"]
    verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-acc-binding
subjects:
  - kind: ServiceAccount
    name: crd-account
    apiGroup: 