apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homework-ingress
  namespace: homework
  annotations:
    nginx.ingress.kubernetes.io/app-root: /index.html
spec:
  rules:
  - host: approot.bar.com
  - http:
      paths:
      - path: /homepage
        #pathType: ImplementationSpecific
        pathType: Prefix
        backend:
          service:
            name: homework-service
            port:
              number: 80