apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homework-pvc
  namespace: homework

spec:
  storageClassName: ""
  volumeName: homework-pv


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: homework-pv

spec:
  storageClassName: ""
  claimRef:
    name: homework-pvc
    namespace: homework