appName: homework

namespace: homework-helm

persistentVolume:
  name: homework-pv

storageClass:
  name: low-latency

persistentVolumeClaim:
  name: homework-pvc

ingress:
  name: homework-ingress

service:
  name: homework-service
  spec:
    type: ClusterIp
    ports:
      protocol: TCP
      port: 80
      targetPort: 8000

deployment: 
  name: homework-deployment
  spec:
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 35%
    replicas: 3

  template:
    spec:
      containers:
        name: webserver
        image: nginx
        tag: latest
        ports:
          containerPort: 8000
      initContainers:
        name: init-container
        image: busybox


readinessProbe:
  httpGet:
    path: /index.html
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 5