apiVersion: v1 
kind: ServiceAccount
metadata:
  name: monitoring
  namespace: homework
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: cd
  namespace: homework
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: homework
  name: homework-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get", "post"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: homework
  name: admin
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homework-binding
  namespace: homework
subjects:
  - kind: ServiceAccount
    name: monitoring
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: homework-role
  apiGroup: rbac.authorization.k8s.io
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-role-binding
  namespace: homework
subjects:
  - kind: ServiceAccount
    name: cd
    apiGroup: ""
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io

