apiVersion: v1 
kind: ConfigMap
metadata:
  name: homework-cm
  namespace: {{ .Values.namespace }}
data:
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"

  # file-like keys
  test.html: |-
    <!DOCTYPE html>
    <html>
        <head>
            <title>PolyControl</title>
        </head>
        <body>
            <h1>This is a Heading</h1>
        </body>
    </html>

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm
  namespace: {{ .Values.namespace }}
data:
  default.conf: |-
    server {
            listen 8000 default_server;
            root /homework;
            server_name  _;
            index index.php index.html;
            location / {
                try_files $uri $uri/ /index.php?$args;
            }

            location ~ \.php$ {
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass 127.0.0.1:9000;
                fastcgi_index index.php;
                include fastcgi_params;
                fastcgi_param   PATH_INFO       $fastcgi_path_info;
                fastcgi_param   SCRIPT_FILENAME $document_root$fastcgi_script_name;
            }

            location /conf/file {
                root /homework/conf/;
                index test.html;
            }
        }