apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}

spec:
  strategy:
    type: {{ .Values.deployment.spec.strategy.type }}
    rollingUpdate:
      maxUnavailable: {{ .Values.deployment.spec.strategy.rollingUpdate.maxUnavailable}}
  replicas: {{ .Values.deployment.spec.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      serviceAccountName: monitoring
  
      containers:
      - name: {{ .Values.deployment.template.spec.containers.name }}
        image: "{{ .Values.deployment.template.spec.containers.image}}:{{ .Values.deployment.template.spec.containers.image}}"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            cpu: "300m"
            memory: "128Mi"
        ports:
          - containerPort: {{ .Values.deployment.template.spec.containers.ports.containerPort}}
            name: nginx-web-view
        volumeMounts:
        - name: homework-volume
          mountPath: /homework
        - name: homework-cm-layout
          mountPath: /homework/conf/
        - name: nginxconf
          mountPath: /etc/nginx/conf.d
          readOnly: true
        lifecycle:
          preStop:
            exec:
              command: ['bash', '-c', 'rm /homework/index.html']
        {{- if .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        {{- end }}


      initContainers:
      - name: {{ .Values.deployment.template.spec.initContainers.name }}
        image: {{ .Values.deployment.template.spec.initContainers.image }}
        command: ['wget', '-O', '/init/index.html', 'http://info.cern.ch']
        volumeMounts:
        - name: homework-volume
          mountPath: /init

      
      volumes: 
      - name: homework-volume
        persistentVolumeClaim:
          claimName: homework-pvc
      - name: homework-cm-layout
        configMap:
          name: homework-cm
      - name: nginxconf
        configMap:
          defaultMode: 256
          name: nginx-cm
          optional: false