apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentVolumeClaim.name }}
  namespace: {{ .Values.namespace }}

spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storageClass.name }}
  resources:
    requests:
      storage: 500Mi
  #storageClassName: ""
  volumeName: {{ .Values.persistentVolume.name }}


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolume.name }}
  namespace: {{ .Values.namespace }}

spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  #storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  claimRef:
     name: {{ .Values.persistentVolumeClaim.name }}
     namespace: {{ .Values.namespace }}
  hostPath:
    path: "/tmp/data"