apiVersion: v1 
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.spec.type }}
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: {{ .Values.service.spec.ports.protocol }}
      port: {{ .Values.service.spec.ports.port }}
      targetPort: {{ .Values.service.spec.ports.trargetPort }}