apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework-deployment
  labels:
    app: homework-pod

spec:
  replicas: 3
  selector:
    matchLabels:
      app: homework
  template:
    metadata:
      labels:
        app: homework
    
    spec:
      containers:
      - name: webserver
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 8000
        volumeMounts:
        - name: homework-volume
          mountPath: /homework
        lifecycle:
          postStart:
            exec:
              command: ['bash', '-c', 'rm /homework/index.html']



      initContainers:
      - name: init-container
        image: busybox
        command:
        - wget
        - "-O"
        - "/init/index.html"
        - http://info.cern.ch
        volumeMounts:
        - name: homework-volume
          mountPath: /init
      
      volumes: 
      - name: homework-volume
        emptyDir: {}
