apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homework-pvc
  namespace: homework

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  #storageClassName: ""
  volumeName: homework-pv


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: homework-pv
  namespace: homework

spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  #storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  claimRef:
     name: homework-pvc
     namespace: homework
  hostPath:
    path: "/tmp/data"