apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx-pod
  namespace: homework
spec:
  containers:
  - name: webserver
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8000
    volumeMounts:
    - name: homework-volume
      mountPath: /homework
  initContainers:
  - name: init-container
    image: busybox
    command:
    - wget
    - "-O"
    - "/init/index.html"
    - http://info.cern.ch
    volumeMounts:
    - name: homework-volume
      mountPath: /init
  
  volumes: 
  - name: homework-volume
    emptyDir: {}
    
  lifecycle:
    postStart:
      exec:
        command: ['bash', '-c', 'rm /homework/index.html']
